version: '3'
services:
  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    cap_add:
      - "SYS_NICE"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ifeanyi
      - POSTGRES_DB=dfscore_dev_2
    container_name: "beans"