spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DB_HOST:192.168.17.20}:${DB_PORT:5432}/${DB_NAME:dfscore_dev_2}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:ifeanyi}
